# © MNELAB developers
#
# License: BSD (3-clause)

"""Parse `CHANGELOG.md` into structured releases.

The changelog is the single source of truth for release notes. It is rendered in
three places, all of which go through this module: the *Help – What's New* dialog,
the generated `docs/releases.md` page, and the body of each GitHub release (both
generated by `tools/changelog.py`).
"""

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

#: version label of the section collecting unreleased changes
UNRELEASED = "UNRELEASED"

#: placeholder date used by `tools/release.py bump` for an unreleased section
UNDATED = "YYYY-MM-DD"

#: marks the point in `CHANGELOG.md` below which every entry was inherited from
#: upstream MNELAB instead of being released from this fork
INHERITED_MARKER = "<!-- inherited upstream history -->"

_VERSION_RE = re.compile(r"^## \[([^\]]+)\](?:\s*[·-]\s*(\S+))?\s*$")
_SECTION_RE = re.compile(r"^### +(.+?)\s*$")
_ENTRY_RE = re.compile(r"^[-*] +(.*)$")
_NUMERIC_RE = re.compile(r"^\d+(\.\d+)*")


@dataclass
class Section:
    """One `### ✨ Added`-style group of entries within a release."""

    title: str
    entries: list[str] = field(default_factory=list)


@dataclass
class Release:
    """One `## [1.2.3] · 2026-01-01`-style section of the changelog."""

    version: str
    date: str | None = None
    sections: list[Section] = field(default_factory=list)
    inherited: bool = False

    @property
    def released(self):
        """Whether this section describes a version that actually shipped."""
        return self.version != UNRELEASED and self.date not in (None, UNDATED)

    @property
    def tag(self):
        """Git tag corresponding to this release."""
        return f"v{self.version}"

    @property
    def entries(self):
        """All entries of all sections, in order."""
        return [entry for section in self.sections for entry in section.entries]


def parse_changelog(text):
    """Parse changelog Markdown into a list of `Release` objects.

    Entries wrapped over several lines are joined into a single line. Everything
    below `INHERITED_MARKER` is flagged as inherited upstream history.

    Parameters
    ----------
    text : str
        Contents of a `CHANGELOG.md` file.

    Returns
    -------
    list of Release
        Releases in file order (newest first).
    """
    releases = []
    inherited = False
    for line in text.splitlines():
        if line.strip() == INHERITED_MARKER:
            inherited = True
            continue
        if match := _VERSION_RE.match(line):
            version, date = match.group(1), match.group(2)
            releases.append(Release(version=version, date=date, inherited=inherited))
            continue
        if not releases:  # skip any preamble above the first version heading
            continue
        release = releases[-1]
        if match := _SECTION_RE.match(line):
            release.sections.append(Section(title=match.group(1)))
            continue
        if match := _ENTRY_RE.match(line):
            if not release.sections:  # entries before any `###` heading
                release.sections.append(Section(title=""))
            release.sections[-1].entries.append(match.group(1).strip())
            continue
        if line.strip() and line.startswith((" ", "\t")):  # wrapped entry
            if release.sections and release.sections[-1].entries:
                entries = release.sections[-1].entries
                entries[-1] = f"{entries[-1]} {line.strip()}"
    return releases


def find_changelog():
    """Return the path of the bundled or in-tree `CHANGELOG.md`, or `None`.

    Standalone builds ship the changelog next to `LICENSE` and `NOTICE`, so the
    PyInstaller extraction directory is searched first, followed by the package
    directory and the repository root of a development checkout.
    """
    candidates = []
    if bundle_dir := getattr(sys, "_MEIPASS", None):
        candidates.append(Path(bundle_dir) / "CHANGELOG.md")
    here = Path(__file__).resolve()
    candidates.append(here.parent / "CHANGELOG.md")
    candidates.append(here.parents[2] / "CHANGELOG.md")
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    return None


def load_releases(path=None):
    """Load and parse the changelog, returning an empty list if it is missing.

    Parameters
    ----------
    path : str | Path | None
        Changelog to read; located automatically with `find_changelog` if `None`.

    Returns
    -------
    list of Release
        Releases in file order (newest first), empty if no changelog was found.
    """
    if path is None:
        path = find_changelog()
    if path is None:
        return []
    try:
        text = Path(path).read_text(encoding="utf-8")
    except OSError:
        return []
    return parse_changelog(text)


def find_release(releases, version):
    """Return the release matching `version` (with or without a leading `v`)."""
    wanted = str(version).lstrip("vV")
    for release in releases:
        if release.version == wanted:
            return release
    return None


def version_sort_key(version):
    """Sort key ordering numeric version prefixes, with `UNRELEASED` on top."""
    if version == UNRELEASED:
        return (1, ())
    match = _NUMERIC_RE.match(version)
    parts = tuple(int(p) for p in match.group(0).split(".")) if match else ()
    return (0, parts)
